---
collections:
  - name: community.docker
    version: ">=3.10.0"
  - name: community.general
    version: ">=9.0.0"   # timezone, sefcontext
  - name: ansible.posix
    version: ">=1.5.0"   # authorized_key, selinux, seboolean
